export type Ingredient = { name: string; grams: number; note?: string };
export type Recipe = { id: string; title: string; cuisine: string; description: string; emoji: string; minutes: number; ingredients: Ingredient[]; steps: string[]; benefits: string[]; nutrition: {calories:number; protein:number; carbs:number; fat:number; fiber:number} };
// Approximate generic reference values per 100 g: kcal, protein, carbs, fat, fiber.
// Dry grains and raw produce unless the ingredient explicitly says cooked.
const nutrients: Record<string, number[]> = {
  egg:[143,12.6,0.7,9.5,0],tomato:[18,.9,3.9,.2,1.2],onion:[40,1.1,9.3,.1,1.7],spinach:[23,2.9,3.6,.4,2.2],
  paneer:[265,18.3,1.2,20.8,0],tofu:[144,17.3,2.8,8.7,2.3],chicken:[120,22.5,0,2.6,0],potato:[77,2,17.5,.1,2.2],
  rice:[365,7.1,80,.7,1.3],"cooked rice":[130,2.7,28.2,.3,.4],pasta:[371,13,75,1.5,3.2],noodles:[371,13,74,1.5,3],
  bread:[265,9,49,3.2,2.7],tortilla:[312,8.3,52,8.3,3.3],oats:[379,13.2,67.7,6.5,10.1],flour:[364,10.3,76.3,1,2.7],
  chickpea:[164,8.9,27.4,2.6,7.6],lentil:[116,9,20,.4,7.9],bean:[127,8.7,22.8,.5,6.4],
  carrot:[41,.9,9.6,.2,2.8],broccoli:[34,2.8,6.6,.4,2.6],pepper:[31,1,6,.3,2.1],mushroom:[22,3.1,3.3,.3,1],
  cucumber:[15,.7,3.6,.1,.5],lettuce:[15,1.4,2.9,.2,1.3],corn:[86,3.3,19,1.4,2],peas:[81,5.4,14.5,.4,5.7],
  cheese:[403,25,1.3,33,0],yogurt:[61,3.5,4.7,3.3,0],milk:[61,3.2,4.8,3.3,0],
  banana:[89,1.1,22.8,.3,2.6],apple:[52,.3,13.8,.2,2.4],avocado:[160,2,8.5,14.7,6.7],
  garlic:[149,6.4,33.1,.5,2.1],ginger:[80,1.8,17.8,.8,2],lemon:[29,1.1,9.3,.3,2.8],
  oil:[884,0,0,100,0],butter:[717,.9,.1,81.1,0],"soy sauce":[53,8.1,4.9,.6,.8],
  cumin:[375,17.8,44.2,22.3,10.5],"garam masala":[350,12,58,12,20],turmeric:[312,9.7,67.1,3.3,22.7],
  "peanut butter":[588,25,20,50,6],salt:[0,0,0,0,0],"black pepper":[251,10,64,3,25]
};
const aliases: Record<string,string> = {
  eggs:"egg",tomatoes:"tomato",onions:"onion",potatoes:"potato",chickpeas:"chickpea",chana:"chickpea","canned chickpeas":"chickpea","cooked chickpeas":"chickpea",
  "chicken breast":"chicken",capsicum:"pepper","bell pepper":"pepper","bell peppers":"pepper",carrots:"carrot",mushrooms:"mushroom",
  "white rice":"rice","brown rice":"rice","leftover rice":"cooked rice","cooked white rice":"cooked rice",curd:"yogurt",yoghurt:"yogurt",
  beans:"bean","kidney beans":"bean","black beans":"bean","cooked beans":"bean",rajma:"bean",lentils:"lentil","cooked lentils":"lentil",dal:"lentil",
  "olive oil":"oil","vegetable oil":"oil","sunflower oil":"oil",bananas:"banana",apples:"apple",tortillas:"tortilla",roti:"tortilla",chapati:"tortilla",
  "wheat flour":"flour",atta:"flour","rolled oats":"oats","green peas":"peas","sweet corn":"corn",lemons:"lemon",jeera:"cumin",haldi:"turmeric",
  "cheddar cheese":"cheese",cheddar:"cheese",mozzarella:"cheese","garlic cloves":"garlic","soya sauce":"soy sauce","peanut butter":"peanut butter"
};
export function normalize(value:string) {
  const clean=value.toLowerCase().trim().replace(/^\d+(?:[./]\d+)?\s*(?:g|kg|grams?|cups?|tbsp|tsp|pieces?)?\s+/,'').replace(/\s+/g,' ').replace(/[.!]+$/,'');
  return aliases[clean] || clean;
}
export const knownIngredients = Object.keys(nutrients);
export function parseIngredients(value:string) {return [...new Set(value.split(/[,;\n]+|\s+and\s+/i).map(normalize).filter(Boolean))].slice(0,40);}
function r(id:string,title:string,cuisine:string,emoji:string,minutes:number,description:string,items:[string,number,string?][],steps:string[],benefits:string[]):Recipe {
 const ingredients=items.map(([name,grams,note])=>({name,grams,note}));
 const totals=ingredients.reduce((out,i)=>out.map((v,k)=>v+(nutrients[i.name]?.[k]||0)*i.grams/100),[0,0,0,0,0]);
 return {id,title,cuisine,emoji,minutes,description,ingredients,steps,benefits,nutrition:{calories:Math.round(totals[0]),protein:Math.round(totals[1]),carbs:Math.round(totals[2]),fat:Math.round(totals[3]),fiber:Math.round(totals[4])}};
}
export const recipes:Recipe[] = [
 r('bhurji','Sunshine egg bhurji','Indian','🍳',15,'Soft scrambled eggs, juicy tomatoes, and a little everyday magic.',[['egg',100,'2 large eggs'],['tomato',100],['onion',50],['oil',5,'1 tsp'],['cumin',1,'½ tsp']],['Chop the onion and tomato. Crack the eggs into a bowl and beat with a fork.','Warm the oil in a pan over medium heat. Add cumin, then onion; cook for 3–4 minutes until soft.','Add tomato and cook for 4 minutes, stirring until softened.','Lower the heat and add the eggs. Stir gently for 2–3 minutes until completely set. Serve hot.'],['Eggs supply protein for muscle maintenance.','Tomatoes add vegetables and a little fiber.']),
 r('paneer','Paneer power scramble','Indian','🧀',20,'A hearty one-pan paneer scramble for a satisfying meal.',[['paneer',125],['tomato',100],['onion',50],['oil',5,'1 tsp'],['garam masala',2,'½ tsp']],['Crumble the paneer and finely chop the onion and tomato.','Heat oil in a pan. Cook the onion over medium heat for 4 minutes.','Add tomato and garam masala. Cook for 5 minutes, adding a splash of water if it sticks.','Fold in the paneer and cook for 3–4 minutes until heated through. Serve warm.'],['Paneer contributes protein and calcium.','A filling option with a short ingredient list.']),
 r('chana','Cozy chickpea skillet','Indian','🥘',20,'A comforting, gently spiced bowl of chickpeas and tomato.',[['chickpea',180,'cooked or canned, drained'],['tomato',150],['onion',50],['oil',5,'1 tsp'],['garam masala',2,'½ tsp']],['Drain and rinse the cooked chickpeas. Chop the onion and tomato.','Heat the oil and soften the onion for 4 minutes.','Add tomato and garam masala; cook for 5 minutes.','Add chickpeas and 100 ml water. Simmer for 8 minutes, lightly mashing a few to thicken the sauce.'],['Chickpeas provide plant protein.','Legume fiber helps make the meal satisfying.']),
 r('aloo','Golden potato & pea skillet','Indian','🥔',25,'Crisp-edged potatoes and sweet peas with warming cumin.',[['potato',200],['peas',80],['cumin',1],['oil',8]],['Dice the potato into 1 cm cubes and rinse.','Heat oil, add cumin, then potatoes. Stir for 2 minutes.','Add 60 ml water, cover, and cook on medium-low for 12–15 minutes until the potatoes are tender.','Stir in peas and cook for 5 minutes, uncovered. Check that everything is hot and tender.'],['Potatoes provide carbohydrates for energy.','Peas add plant protein and fiber.']),
 r('dal','Easy lentil comfort bowl','Indian','🍲',18,'An easy tomato dal made with already-cooked lentils.',[['lentil',200,'cooked or canned'],['tomato',100],['onion',40],['turmeric',1],['oil',5]],['Use cooked lentils; dry lentils need cooking first according to their package. Chop the vegetables.','Warm oil and cook the onion for 4 minutes. Add tomato and turmeric; cook for 4 more minutes.','Add the cooked lentils and 120 ml water. Simmer for 8 minutes.','Stir well and adjust thickness with a little water. Serve hot.'],['Lentils contribute plant protein and iron.','A fiber-rich meal that uses everyday ingredients.']),
 r('pasta','Tomato twirl pasta','Italian','🍝',22,'A simple tomato-garlic sauce that makes your pasta shine.',[['pasta',80,'dry weight'],['tomato',180],['garlic',6,'2 cloves'],['oil',8]],['Bring a pot of water to a boil. Cook pasta according to the package; reserve a small cup of cooking water.','Chop tomatoes and mince garlic. Warm oil in a frying pan, then cook garlic for 30 seconds.','Add tomatoes and simmer for 10 minutes, crushing them with a spoon.','Drain the pasta and toss into the sauce. Add a splash of reserved water and stir for 1 minute.'],['Pasta supplies carbohydrates for energy.','Tomatoes bring vegetables to a simple meal.']),
 r('spinach-pasta','Green garden pasta','Italian','🥬',20,'Garlicky spinach and pasta with a little cheese on top.',[['pasta',80,'dry weight'],['spinach',100],['garlic',6],['cheese',20],['oil',5]],['Cook pasta according to the package directions. Save a little cooking water before draining.','Wash spinach and mince garlic. Warm oil in a pan and cook garlic for 30 seconds.','Add spinach and stir for 2–3 minutes until wilted.','Toss in pasta, cheese, and 2 tablespoons of cooking water. Stir over low heat until coated.'],['Spinach contributes folate and vitamin K.','Cheese adds protein and calcium.']),
 r('frittata','Little garden frittata','Italian','🍳',18,'A fluffy, skillet-sized egg dish with tomato and spinach.',[['egg',100,'2 large eggs'],['spinach',60],['tomato',80],['cheese',20],['oil',5]],['Beat the eggs and grate the cheese. Wash and chop the vegetables.','Heat oil in a small nonstick pan. Cook the tomato for 3 minutes and add spinach until wilted.','Pour in the eggs and sprinkle cheese on top. Cover and cook on low for 7–9 minutes.','Check that the middle is completely set; eggs should reach 71°C if using a thermometer. Slice and serve.'],['Eggs and cheese provide protein.','Spinach adds leafy greens to your meal.']),
 r('bruschetta','Crunchy tomato toast','Italian','🍞',10,'Bright tomatoes on warm, golden garlic toast.',[['bread',80,'2 slices'],['tomato',150],['garlic',3,'1 clove'],['oil',5]],['Dice tomatoes and mix with half the oil.','Toast bread in a toaster or dry pan until crisp on both sides.','Cut the garlic clove and rub lightly over the warm toast.','Spoon on the tomatoes and drizzle with the remaining oil. Eat straight away.'],['A quick way to add tomatoes to a snack.','Bread provides a convenient source of energy.']),
 r('fried-rice','Golden egg fried rice','Asian','🍚',15,'A fast, colorful pan of rice, egg, and crunchy carrots.',[['cooked rice',180,'chilled promptly after cooking'],['egg',50,'1 large egg'],['carrot',60],['peas',50],['soy sauce',10],['oil',5]],['Use properly refrigerated cooked rice. Dice the carrot finely and beat the egg.','Heat oil in a large pan and stir-fry carrot and peas for 4 minutes.','Push vegetables aside, add the egg, and scramble until set.','Add rice and soy sauce. Stir-fry for 4–5 minutes until piping hot throughout; serve immediately and reheat rice only once.'],['Eggs and peas contribute protein.','Carrots and peas add fiber and color.']),
 r('tofu','Tofu broccoli power bowl','Asian','🥦',20,'Golden tofu and crisp broccoli in a savory garlic glaze.',[['tofu',150],['broccoli',180],['garlic',6],['soy sauce',12],['oil',7]],['Drain tofu, pat it dry, and cut into cubes. Cut broccoli into small florets.','Heat oil in a pan. Cook tofu for 6–8 minutes, turning until golden.','Add broccoli and 3 tablespoons of water. Cover and steam for 4 minutes.','Uncover, add garlic and soy sauce, and stir-fry for 2 minutes.'],['Tofu supplies plant-based protein.','Broccoli adds fiber and vitamin C.']),
 r('noodles','Rainbow fridge noodles','Asian','🍜',18,'Slurpable noodles with the crunch of fresh vegetables.',[['noodles',80,'dry weight'],['carrot',60],['pepper',80],['soy sauce',12],['garlic',6],['oil',5]],['Cook noodles according to package directions and drain.','Slice carrot and pepper into thin strips; mince garlic.','Heat oil in a large pan. Stir-fry vegetables for 4–5 minutes, then add garlic for 30 seconds.','Add noodles and soy sauce. Toss for 2 minutes until hot throughout.'],['Vegetables add fiber and a range of micronutrients.','Noodles provide carbohydrates for energy.']),
 r('chicken','Garlic chicken & broccoli','Asian','🍗',25,'A simple savory skillet with plenty of protein.',[['chicken',150,'raw, boneless breast'],['broccoli',150],['garlic',6],['soy sauce',12],['oil',7]],['Use a separate board for raw chicken. Cut into bite-sized pieces; wash hands and utensils afterward.','Heat oil in a pan. Cook chicken for 7–9 minutes, turning frequently.','Add broccoli and 50 ml water. Cover and cook for 5 minutes.','Add garlic and soy sauce; cook for 2 more minutes. Confirm chicken reaches 74°C at the center before serving.'],['Chicken provides lean protein.','Broccoli adds vegetables and fiber.']),
 r('quesadilla','Cheesy bean quesadilla','Mexican','🌮',12,'A crisp tortilla with a melty, satisfying bean filling.',[['tortilla',60,'1 large tortilla'],['bean',100,'cooked or canned, drained'],['cheese',35],['tomato',60]],['Drain the cooked beans and lightly mash with a fork. Dice the tomato and grate cheese.','Place the tortilla in a dry pan over medium-low heat.','Spread beans, tomato, and cheese on one half. Fold over and cook for 3–4 minutes per side.','When the filling is hot and the cheese melted, slide onto a board and cut into wedges.'],['Beans contribute fiber and plant protein.','Cheese adds calcium and protein.']),
 r('burrito','Rainbow bean rice bowl','Mexican','🥗',15,'Colorful beans, corn, and rice in one easy bowl.',[['cooked rice',150],['bean',120,'cooked or canned'],['corn',60],['tomato',80],['lemon',15]],['Drain the beans and corn. Dice the tomato.','Heat rice, beans, and corn in a pan with a splash of water until piping hot throughout.','Spoon into a bowl and top with tomato.','Squeeze lemon over the bowl. Use properly refrigerated rice and reheat it only once.'],['Beans add plant protein and fiber.','Rice and corn provide energy.']),
 r('tacos','Sunny egg tacos','Mexican','🌮',12,'Soft eggs and tomato tucked into a warm tortilla.',[['tortilla',60],['egg',100,'2 large eggs'],['tomato',80],['onion',25],['oil',5]],['Finely chop the tomato and onion. Beat the eggs in a bowl.','Heat oil in a small pan and soften the onion for 3 minutes.','Add eggs and stir over low heat until fully set.','Warm tortilla in a dry pan, fill with eggs, and top with fresh tomato.'],['Eggs supply protein.','Tomato adds freshness and a little fiber.']),
 r('salad','Chickpea crunch salad','Mediterranean','🥗',10,'A fresh bowl of chickpeas, cucumber, and juicy tomato.',[['chickpea',160,'cooked or canned, drained'],['cucumber',100],['tomato',100],['lemon',20],['oil',5]],['Drain and rinse the cooked chickpeas.','Wash and chop cucumber and tomato into bite-sized pieces.','Mix lemon juice and oil in a bowl.','Add chickpeas and vegetables, toss well, and serve.'],['Chickpeas add plant protein and fiber.','Fresh vegetables add variety and hydration.']),
 r('shakshuka','Tomato nest eggs','Mediterranean','🍳',25,'Eggs gently cooked in a rich, rustic tomato pan.',[['egg',100,'2 large eggs'],['tomato',250],['onion',50],['garlic',6],['oil',5]],['Chop the vegetables and mince garlic.','Heat oil, cook onion for 4 minutes, then garlic for 30 seconds.','Add tomatoes and simmer for 10 minutes, crushing them into a thick sauce.','Make two wells and crack an egg into each. Cover and cook for 7–9 minutes until whites and yolks are firm.'],['Eggs provide protein for everyday needs.','A generous tomato base adds vegetables.']),
 r('yogurt','Banana oat breakfast bowl','Global','🍌',5,'A creamy, no-cook bowl for a sweet little energy boost.',[['yogurt',180],['oats',40,'rolled oats'],['banana',100]],['Spoon yogurt into a bowl.','Mix in rolled oats. Let stand for 5 minutes if you prefer them softer.','Slice the banana and arrange on top.','Serve straight away, or refrigerate covered and eat within a day.'],['Oats contribute fiber.','Yogurt provides protein and calcium.']),
 r('omelette','Your everyday omelette','Global','🍳',10,'Simple, fluffy eggs with a handful of spinach.',[['egg',100,'2 large eggs'],['spinach',50],['oil',5]],['Wash and roughly chop the spinach. Beat eggs in a bowl.','Heat oil in a small nonstick pan. Wilt spinach for 1–2 minutes.','Pour in eggs, tilt the pan to spread evenly, and cook over low heat.','Once completely set, fold in half and serve.'],['Eggs supply protein.','Spinach adds leafy greens and folate.']),
 r('avocado','Avocado toast adventure','Global','🥑',8,'Creamy avocado and fresh tomato on crisp toast.',[['bread',80,'2 slices'],['avocado',80],['tomato',60],['lemon',10]],['Toast the bread until crisp.','Mash avocado with lemon juice.','Slice tomato. Spread avocado on warm toast.','Top with tomato and serve immediately.'],['Avocado contributes unsaturated fats and fiber.','Bread supplies carbohydrates for energy.']),
 r('oats','Peanut banana porridge','Global','🥣',10,'Warm oats with banana and a nutty swirl.',[['oats',50],['milk',180],['banana',80],['peanut butter',15]],['Combine oats and milk in a small saucepan.','Bring to a gentle simmer and cook for 5–7 minutes, stirring often. Add a splash of water if too thick.','Slice the banana.','Spoon oats into a bowl, stir in peanut butter, and top with banana.'],['Oats provide fiber.','Milk and peanut butter contribute protein.']),
 r('grilled-cheese','Golden cheese toastie','Global','🥪',10,'A crisp, comforting toastie with a melty middle.',[['bread',80,'2 slices'],['cheese',40],['butter',5]],['Spread a thin layer of butter on one side of each bread slice.','Place cheese between the unbuttered sides.','Cook in a pan over medium-low heat for 3–4 minutes per side.','When both sides are golden and the cheese has melted, slice and serve.'],['Cheese supplies protein and calcium.','A compact, energy-dense meal.']),
 r('potato-eggs','Potato & egg breakfast skillet','Global','🥔',25,'Golden potatoes with eggs for a hearty start.',[['potato',180],['egg',100,'2 large eggs'],['onion',40],['oil',7]],['Dice potato and onion.','Heat oil, add potato and 60 ml water. Cover and cook for 12–15 minutes until tender.','Add onion and cook uncovered for 4 minutes.','Beat eggs and pour into the pan. Stir gently until fully set and hot throughout.'],['Eggs add protein.','Potatoes supply carbohydrates and potassium.'])
];
export type Match = Recipe & { matched: string[]; missing: string[]; score: number };
export function findRecipes(ingredients:string[], cuisine:string, mood:string, basics:boolean):Match[] {
 const pantry = new Set(ingredients.map(normalize)); if(basics) ['oil','salt','black pepper'].forEach(x=>pantry.add(x));
 return recipes.filter(r=>cuisine==='Global'||r.cuisine===cuisine).map(r=>{
  const matched=r.ingredients.filter(i=>pantry.has(i.name)).map(i=>i.name),missing=r.ingredients.filter(i=>!pantry.has(i.name)).map(i=>i.name);
  const coreMatch=matched.filter(x=>!['oil','salt','black pepper','cumin','garam masala','turmeric','garlic','lemon','soy sauce'].includes(x)).length;
  const score=matched.length/r.ingredients.length*100 -missing.length*9 +(mood==='quick'?(30-r.minutes)*.35:mood==='protein'?r.nutrition.protein*.35:mood==='light'?-r.nutrition.calories*.015:0);
  return {...r,matched,missing,score,coreMatch};
 }).filter(r=>r.coreMatch>0).sort((a,b)=>(a.missing.length===0?-1:0)-(b.missing.length===0?-1:0)||b.score-a.score).slice(0,6);
}
